# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qr-code-sample-app"
client_id = "20b69534cf6eef8e23acadfccb21b1f4"
application_url = "https://payday-instructor-rss-saver.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_discounts"

[auth]
redirect_urls = [
  "https://payday-instructor-rss-saver.trycloudflare.com/auth/callback",
  "https://payday-instructor-rss-saver.trycloudflare.com/auth/shopify/callback",
  "https://payday-instructor-rss-saver.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c057cdd6.myshopify.com"
